version: '3.9'

services:
  php:
    image: php:v1
    build: ./dockerfile/php
    container_name: line_bot_php
    volumes:
      - ./dockerfile/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    ports:
      - 8000:80
    links:
      - mysql:mysql
  mysql:
    image: mysql:8.0
    container_name: line_bot_mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev