name: php-cs-fixer

on: 
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v2
      - name: install php-cs-fixer
        run: |
          composer install --no-scripts --no-progress
          ./vendor/bin/php-cs-fixer --version
      - name: fix the files
        run: |
          ./vendor/bin/php-cs-fixer fix .
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: php-cs-fixer by github actions
